### ISSUE TITLE
make module check for valid rest url 

### ISSUE THREAD

**Issue by WianVos** [xebialabs/puppet-xldeploy#54]
A xldeploy rest url should always and with /deployit .. 

will need to do a check for that otherwise results may vary

**Comment by ltutar** [comment]
At the page https://forge.puppetlabs.com/xebialabs/xldeploy there is only reference to rest API with /xldeploy
Maybe somebody can change the documentation

Met vriendelijke groet,

Levent


Levent Tutar * Senior Consultant
Xebia BV * Utrechtseweg 49 * 1213 TL Hilversum * The Netherlands
mobile +31 641452164  * office +31 35 5381921 * email ltutar@xebia.com<mailto:ltutar@xebia.com>

Visit Xebia on web at  www.xebia.com<http://www.xebia.com>

On 06 Mar 2015, at 13:32, WianVos <notifications@github.com<mailto:notifications@github.com>> wrote:


A xldeploy rest url should always and with /deployit ..

will need to do a check for that otherwise results may vary

**Comment by ltutar** [comment]
Do not check that. You can use a different context root with the property http.context.root in deployit.conf. 
BTW. the documentation at https://github.com/xebialabs/puppet-xldeploy is only referring to /xldeploy

**Comment by WianVos** [comment]
true but the rest url then ends with <context_root>/deployit .. 
the resturl always and on /deployit

**Comment by ltutar** [comment]
I get you
